### ISSUE TITLE
Scripts throwing LLVM OOM

### ISSUE THREAD

**Issue by mmarchini** [brendangregg/bpf-perf-tools-book#2]
Found two scripts affected by https://github.com/iovisor/bpftrace/issues/528:

- soaccept
- soconnect

There might be other scripts affected by this.

**Comment by brendangregg** [comment]
I added a 1 Gbyte memory limit to stop this issue causing too much pain ( https://github.com/iovisor/bpftrace/pull/636 ) and @mmarchini has a draft PR to properly fix it ( https://github.com/iovisor/bpftrace/pull/711 ).

**Comment by brendangregg** [comment]
I just tested on the latest bpftrace (v0.9.2-153-ga104) and these work fine. The bpftrace ticket has also been closed. Closing here as well.
