### ISSUE TITLE
minor errata: ch. 9 "strategy" section is misnumbered

### ISSUE THREAD

**Issue by alexeldeib** [brendangregg/bpf-perf-tools-book#9]
From the Safari version: 
![image](https://user-images.githubusercontent.com/6800857/68001041-9d044800-fc1f-11e9-980b-ad69e2df197f.png)

**Comment by brendangregg** [comment]
Sorry and thanks; the extra step 1 should be 2a. This looks like an Safari conversion error, and the only eBook version I saw was the PDF version where it is correct.

Added to Errata and closing here. http://www.brendangregg.com/bpf-performance-tools-book.html#errata
